antora:
  extensions:
  - '@springio/antora-extensions/partial-build-extension'
  # atlas-extension must be before latest-version-extension so latest versions are applied to imported versions
  - '@antora/atlas-extension'
  - require: '@springio/antora-extensions/latest-version-extension'
  - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
  - '@antora/collector-extension'
  - require: '@springio/antora-extensions/root-component-extension'
    root_component_name: 'amqp'
  - '@springio/antora-extensions/static-page-extension'
site:
  title: Spring AMQP
  url: https://docs.spring.io/spring-amqp/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-amqp
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [ main,'({3..9}).+({0..9}).x', '!(3.0.x)' ]
    tags: [ 'v({3..9}).+({0..9}).+({0..9})?(-{RC,M}+({0..9}))', '!(v3.0.*)', '!(v3.1.0?(-{RC,M}+({0..9})))']
    start_path: src/reference/antora
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-amqp
    page-related-doc-projects: integration,framework
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.9/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
